import { invoke } from "@tauri-apps/api/core";
import type { Block, HarnessId } from "../../sessions/model/session";
import type { NativeProvider } from "./providerSessions";
import { PROVIDER_LABEL } from "./conversationSummary";

/** One display-only item from a provider's own transcript. */
export type HistoryItem = {
  id: string;
  role: "user" | "assistant" | "tool";
  text: string;
  /** Epoch ms when the provider recorded it, when present. */
  at?: number;
  /** Stable provider record identity, when the transcript supplies one. */
  nativeId?: string;
};

export const HISTORY_BLOCK_PREFIX = "history:";
/** Per-message cap; provider transcripts embed very large pastes. */
const MAX_ITEM_CHARS = 20_000;
/** Messages shown per step; "Show earlier" reveals more. */
export const HISTORY_PAGE_ITEMS = 200;

export function isHistoryBlock(block: Pick<Block, "id">): boolean {
  return block.id.startsWith(HISTORY_BLOCK_PREFIX);
}

function cap(text: string): string {
  const trimmed = text.trim();
  const chars = [...trimmed];
  return chars.length <= MAX_ITEM_CHARS
    ? trimmed
    : `${chars.slice(0, MAX_ITEM_CHARS).join("")}… [truncated]`;
}

function record(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

function at(raw: Record<string, unknown>): { at?: number } {
  if (typeof raw.timestamp !== "string") return {};
  const parsed = Date.parse(raw.timestamp);
  return Number.isFinite(parsed) ? { at: parsed } : {};
}

/** Text the provider injects on the user's behalf; not something the user typed. */
function injectedUserText(text: string): boolean {
  return /^\s*<(environment_context|user_instructions|command-name|command-message|command-args|local-command|system-reminder|turn_aborted)/.test(
    text,
  ) || text.startsWith("Caveat: The messages below were generated by the user");
}

function parseLines(jsonl: string): Record<string, unknown>[] {
  const out: Record<string, unknown>[] = [];
  for (const raw of jsonl.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) continue;
    try {
      const rec = record(JSON.parse(line));
      if (rec) out.push(rec);
    } catch {
      // A torn or foreign line is skipped; the rest still renders.
    }
  }
  return out;
}

function claudeItems(lines: Record<string, unknown>[]): Omit<HistoryItem, "id">[] {
  const items: Omit<HistoryItem, "id">[] = [];
  for (const rec of lines) {
    if (rec.isSidechain === true || rec.isMeta === true) continue;
    if (rec.type !== "user" && rec.type !== "assistant") continue;
    const message = record(rec.message);
    if (!message) continue;
    const role = rec.type;
    const content = message.content;
    const texts: string[] = [];
    const tools: string[] = [];
    if (typeof content === "string") texts.push(content);
    else if (Array.isArray(content))
      for (const part of content) {
        const block = record(part);
        if (!block) continue;
        if (block.type === "text" && typeof block.text === "string")
          texts.push(block.text);
        else if (
          role === "assistant" &&
          block.type === "tool_use" &&
          typeof block.name === "string"
        )
          tools.push(block.name);
        // tool_result, thinking and images are not conversation text.
      }
    const text = texts.join("\n\n").trim();
    const identity = typeof rec.uuid === "string" ? { nativeId: rec.uuid } : {};
    if (text && !(role === "user" && injectedUserText(text)))
      items.push({ role, text: cap(text), ...at(rec), ...identity });
    for (const name of tools) items.push({ role: "tool", text: name, ...at(rec), ...identity });
  }
  return items;
}

function codexItems(lines: Record<string, unknown>[]): Omit<HistoryItem, "id">[] {
  const items: Omit<HistoryItem, "id">[] = [];
  for (const rec of lines) {
    if (rec.type !== "response_item") continue;
    const payload = record(rec.payload);
    if (!payload) continue;
    if (payload.type === "message") {
      const role =
        payload.role === "assistant"
          ? "assistant"
          : payload.role === "user"
            ? "user"
            : null;
      if (!role || !Array.isArray(payload.content)) continue;
      const wanted = role === "user" ? "input_text" : "output_text";
      const text = payload.content
        .map((part) => record(part))
        .filter((part) => part?.type === wanted && typeof part.text === "string")
        .map((part) => String(part?.text))
        .join("\n\n")
        .trim();
      if (text && !(role === "user" && injectedUserText(text)))
        items.push({ role, text: cap(text), ...at(rec) });
    } else if (
      (payload.type === "function_call" ||
        payload.type === "custom_tool_call" ||
        payload.type === "local_shell_call") &&
      (typeof payload.name === "string" || payload.type === "local_shell_call")
    ) {
      items.push({
        role: "tool",
        text: typeof payload.name === "string" ? payload.name : "shell",
        ...at(rec),
      });
    }
  }
  return items;
}

/**
 * Ordered, display-only items from one chunk of a Claude JSONL or Codex
 * rollout. Unknown envelopes are skipped, never thrown: schemas drift.
 */
export function parseProviderHistory(
  provider: NativeProvider,
  jsonl: string,
  idPrefix: string,
): HistoryItem[] {
  const lines = parseLines(jsonl);
  const items = provider === "claude" ? claudeItems(lines) : codexItems(lines);
  return items.map((item, index) => ({
    ...item,
    id: `${HISTORY_BLOCK_PREFIX}${idPrefix}:${index}`,
  }));
}

/** Transcript blocks for display only; never stored, sent or counted as turns. */
export function historyBlocks(
  items: readonly HistoryItem[],
  provider: NativeProvider,
  options: { hasEarlier: boolean; hiddenCount: number },
): Block[] {
  const label = PROVIDER_LABEL[provider];
  const blocks: Block[] = items.map((item) =>
    item.role === "tool"
      ? {
          id: item.id,
          role: "tool",
          text: item.text,
          tool: { title: item.text, kind: "other", status: "completed" },
        }
      : {
          id: item.id,
          role: item.role,
          text: item.text,
          ...(item.at && item.role === "user" ? { startedAt: item.at } : {}),
        },
  );
  blocks.push({
    id: `${HISTORY_BLOCK_PREFIX}divider`,
    role: "system",
    text: `Earlier in ${label === "Claude" ? "Claude Code" : label}${
      options.hasEarlier || options.hiddenCount > 0
        ? " · older messages not shown yet"
        : ""
    }`,
  });
  return blocks;
}

/**
 * Drop provider items recorded at or after MonoCode's own first turn. Those
 * turns are already in the session's blocks (the provider file also holds
 * them once the chat has been continued here), so showing both would repeat them.
 */
export function trimHistoryBefore(
  items: readonly HistoryItem[],
  cutoffMs: number | undefined,
  representedNativeIds?: ReadonlySet<string>,
): HistoryItem[] {
  // Provider timestamps can precede the moment MonoCode receives the phone turn.
  // Trim the entire replayed suffix, including undated responses and tools.
  const boundary = items.findIndex((item) => item.nativeId !== undefined && representedNativeIds?.has(item.nativeId));
  const earlier = boundary < 0 ? items : items.slice(0, boundary);
  if (cutoffMs === undefined) return [...earlier];
  return earlier.filter((item) => item.at === undefined || item.at < cutoffMs);
}

/** What the transcript renders: history above the session's own blocks. */
export function withHistory(history: Block[], blocks: Block[]): Block[] {
  return history.length === 0 ? blocks : [...history, ...blocks];
}

export type HistoryChunk = { text: string; start: number; hasEarlier: boolean };

export type HistoryLoader = {
  source: (sessionId: string) => Promise<{ key: string } | null>;
  read: (input: {
    key: string;
    provider: NativeProvider;
    accountId: string;
    end?: number;
  }) => Promise<HistoryChunk>;
};

export const tauriHistoryLoader: HistoryLoader = {
  source: (sessionId) =>
    invoke<{ key: string; cwd: string } | null>(
      "provider_sessions_for_session",
      { sessionId },
    ),
  read: ({ key, provider, accountId, end }) =>
    invoke<HistoryChunk>("provider_sessions_history", {
      key,
      provider,
      accountId,
      end: end ?? null,
    }),
};

export type NativeHistoryState =
  | { status: "none" }
  | { status: "loading" }
  | { status: "error"; message: string }
  | {
      status: "ready";
      provider: NativeProvider;
      /** Oldest first, everything parsed so far. */
      items: HistoryItem[];
      visible: number;
      hasEarlier: boolean;
      loadingEarlier: boolean;
      /** Set when an earlier chunk failed to load; the loaded part stays. */
      earlierError?: string;
    };

const NONE: NativeHistoryState = { status: "none" };

/**
 * Per-session read-only history cache. Loaded when a Claude/Codex chat with a
 * native binding is shown; read through the provider's own store, never
 * written, never persisted as MonoCode turns, never sent to the provider.
 */
export class NativeHistoryStore {
  private states = new Map<string, NativeHistoryState>();
  private started = new Set<string>();
  private cursors = new Map<string, { key: string; accountId: string; end: number }>();
  private listeners = new Set<() => void>();
  private version = 0;

  constructor(private readonly loader: HistoryLoader = tauriHistoryLoader) {}

  subscribe = (listener: () => void): (() => void) => {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  };
  getVersion = (): number => this.version;
  get(sessionId: string): NativeHistoryState {
    return this.states.get(sessionId) ?? NONE;
  }

  private set(sessionId: string, state: NativeHistoryState): void {
    this.states.set(sessionId, state);
    this.version += 1;
    for (const listener of [...this.listeners]) listener();
  }

  /** Once per session id per app run; `reload` retries a failure. */
  async ensureLoaded(
    sessionId: string,
    harness: HarnessId,
    accountId: string,
    reload = false,
  ): Promise<void> {
    if (harness !== "claude" && harness !== "codex") return;
    if (this.started.has(sessionId) && !reload) return;
    this.started.add(sessionId);
    this.set(sessionId, { status: "loading" });
    try {
      const source = await this.loader.source(sessionId);
      if (!this.started.has(sessionId)) return;
      if (!source) {
        this.set(sessionId, NONE);
        return;
      }
      const chunk = await this.loader.read({ key: source.key, provider: harness, accountId });
      if (!this.started.has(sessionId)) return;
      this.cursors.set(sessionId, { key: source.key, accountId, end: chunk.start });
      const items = parseProviderHistory(harness, chunk.text, String(chunk.start));
      this.set(sessionId, {
        status: "ready",
        provider: harness,
        items,
        visible: Math.min(items.length, HISTORY_PAGE_ITEMS),
        hasEarlier: chunk.hasEarlier,
        loadingEarlier: false,
      });
    } catch (error) {
      if (!this.started.has(sessionId)) return;
      this.set(sessionId, {
        status: "error",
        message: error instanceof Error ? error.message : String(error),
      });
    }
  }

  /** Reveal more parsed messages, loading an earlier file chunk when they run out. */
  async showEarlier(sessionId: string): Promise<void> {
    const state = this.get(sessionId);
    if (state.status !== "ready" || state.loadingEarlier) return;
    if (state.visible < state.items.length) {
      this.set(sessionId, {
        ...state,
        visible: Math.min(state.items.length, state.visible + HISTORY_PAGE_ITEMS),
      });
      return;
    }
    const cursor = this.cursors.get(sessionId);
    if (!state.hasEarlier || !cursor) return;
    this.set(sessionId, { ...state, loadingEarlier: true, earlierError: undefined });
    try {
      const chunk = await this.loader.read({
        key: cursor.key,
        provider: state.provider,
        accountId: cursor.accountId,
        end: cursor.end,
      });
      const latest = this.get(sessionId);
      if (latest.status !== "ready" || !this.started.has(sessionId)) return;
      this.cursors.set(sessionId, { ...cursor, end: chunk.start });
      const earlier = parseProviderHistory(state.provider, chunk.text, String(chunk.start));
      const items = [...earlier, ...latest.items];
      this.set(sessionId, {
        ...latest,
        items,
        visible: Math.min(items.length, latest.visible + HISTORY_PAGE_ITEMS),
        hasEarlier: chunk.hasEarlier,
        loadingEarlier: false,
      });
    } catch (error) {
      const latest = this.get(sessionId);
      if (latest.status !== "ready") return;
      this.set(sessionId, {
        ...latest,
        loadingEarlier: false,
        earlierError: error instanceof Error ? error.message : String(error),
      });
    }
  }

  /** Drop a deleted chat's cache and invalidate any read still in flight. */
  forget(sessionId: string): void {
    this.started.delete(sessionId);
    this.cursors.delete(sessionId);
    if (this.states.delete(sessionId)) {
      this.version += 1;
      for (const listener of [...this.listeners]) listener();
    }
  }
}

export const nativeHistoryStore = new NativeHistoryStore();

/** Messages currently shown, newest `visible` of what has been parsed. */
export function visibleHistoryItems(state: NativeHistoryState): HistoryItem[] {
  if (state.status !== "ready") return [];
  return state.items.slice(state.items.length - state.visible);
}
