"""Author-defined conflict recommendations; measured evidence comes from scratch blobs."""
import json
from pathlib import Path
OUT=Path(__file__).resolve().parents[1]
evidence=json.loads(OUT.joinpath('scripts/conflict-evidence.json').read_text(encoding='utf-8'))
manifest=json.loads(OUT.joinpath('scripts/manifest.json').read_text(encoding='utf-8'))
S='src/features/sessions/';H='src/integrations/harness/';F='src/features/settings/';G='src/features/source-control/'
# name, exact paths, class, local change, upstream change, seam, tests
groups=[
('Version label and generated manifests',['Cargo.lock','Cargo.toml','package-lock.json','package.json','src-tauri/tauri.conf.json'],'mechanical','local5 suffix and Windows installer/archive script','release versions and host/rpm scripts/dependencies','Choose one owner-approved local label; preserve Windows no-sign+NSIS+archive script and union approved upstream scripts/deps. Regenerate affected lock metadata with package-manager tooling; never hand-edit lockfiles.','No behavior unit test; exact six version locations and build commands'),
('Windows native plumbing',['src-tauri/src/'+p for p in ['fs.rs','lib.rs','main.rs','search.rs','window.rs']],'weave','scratch-chat/wallpaper/import/ACP commands, hidden process spawning, acrylic preparation','generated-image/search/clipboard/remote registrations; askpass; macOS Quick windows; Linux glass','Union module/command lists once; keep AtomicU64 and AtomicBool, mpsc/thread/AppHandle/Uuid. Keep ensure_scratch_chat alongside generated-image functions. Run askpass exit check and ACP-auth URL check as independent early exits. Preserve Windows preparation before returning upstream WebviewWindow; retain reveal conditional focus. Build cancellable search command through hidden process helper rather than losing console suppression.','fs reveal tests; ACP tests; window/search tests; manual zero-console check separate'),
('Provider binary authority',['src-tauri/src/harness.rs',H+'core/child.ts'],'new product question','case-insensitive validated override paths, hidden helpers/job cleanup, Cline and official ACP resolver','configured-provider binary paths/args, remote backend abstraction, updater exec output, Unix busy-binary retry','Keep backend canonical resolution and Windows resolved_binary_matches; extend configured resolver with Cline and ACP. Preserve hide_console_window/isolate_child/terminate/job code while adding Unix retry and exec_output. Do not substitute raw Command::new for Windows-aware provider command. D-04 chooses one stored override authority.','harness Windows resolver tests; child.test.ts; ACP/Cline live tests; new legacy-override migration test'),
('Discovery and model picker',['src/integrations/harness/core/availability.ts',S+'ui/ModelPicker.tsx',H+'providers/claude/claudeCatalog.ts',H+'providers/codex/codexCatalog.ts'],'weave','per-provider evidence and lazy ACP handshake, Cline tab, timeout/exit catalog reporting and resolved Claude default alias','shared availability state, per-project visibility, remote model source, configured binary options, version-native Claude IDs','Move local evidenced/error state into one authoritative availability store; include Cline in its Record. Compose project-hidden filters with local per-provider evidence. Local source refresh must still exclude ACP blanket probes; remote source refresh may use host. Keep Claude default/resolved-model fallback and upstream claudeLaunchId concrete IDs. Use distinct Codex probe IDs and upstream configured binary parameters with local exit code/timeout reporting.','ModelPicker.test.ts 440/442; availability.test.ts; models/ClaudeCatalog tests; new split-store regression'),
('Session SQL and bounded search',['src-tauri/src/session_store.rs'],'weave','Windows cwd candidate matching/dedup and v14 queue reconciliation; persisted queue columns','cancellable read-only bounded search, generated-image cleanup lifecycle and restored index checks','Keep current migration lineage through18 and all queue fields in INSERT/SELECT/mapper. Adapt search_sessions_sql to candidate cwd matching (not a single exact cwd), bind budget/limit/cancellation parameters correctly and retain ID dedup. Keep new search budget/truncation behavior; do not restore obsolete SearchRow if unused.','session_store queue migration/round-trip/Windows history tests; bounded search tests; new combined search+legacy-drive fixture'),
('Application lifecycle and send ownership',['src/app/App.tsx'],'weave','scratch Chat, terminal cleanup, queue scheduler, review/Sidechat, native fork send flow, forms/session approvals and human-origin flag','remote sessions, preview tabs, BTW, Operator, usage-limit resumes, multi-project opening, CI repairs, lazy UI','Compose sendTurn with exactly one runNativeBranchSend: build Operator/CI prompt first, then fork wrapper, retain humanAuthored. Keep local queue scheduler and terminal start/forget/kill on every close/removal path; add remote history retention independently. Route local approval scope and remote approval separately without advertising unsupported remote session scope. Retain local flexible diff options while adapting upstream pin/kind.','queueDurability/sessionRemoval/terminalPanes; branchFlow and handoff tests; operator/usage-limit tests; new combined lifecycle regression'),
('Shell navigation and compact drawer',['src/app/shell/MenuBar.tsx','src/app/shell/ProjectRail.tsx','src/app/shell/Sidebar.tsx'],'weave','always-visible menu, SharedHoverHighlight, ChatPanel routing and local project menu','custom keys/autosave menu; extracted useProjectMenu; drawer and remote projects','Union menu imports. Use upstream useProjectMenu rather than duplicate old menu builder, preserving local mode/hover attributes at callers. Keep mode=chat overlay guards and shared highlight. Add upstream drawer only to project sidebar branch; retain mount/performance and remote behavior. Never hide menu behind Alt.','Sidebar/TitleBar/hover tests; drawer/rail tests; new Chat-overlay/drawer distinction'),
('Usage presentation',['src/app/shell/UsageFooter.tsx','src/app/shell/UsageProviderChip.tsx','src/features/providers/model/rateLimits.test.ts'],'new product question','optional percentage-left setting and locale-safe metrics','per-account readiness, Pi usage and remaining-percent default','Union React hooks/types and presentation prop; avoid computing remaining twice. D-06 determines whether local toggle remains meaningful or upstream remaining default replaces it. Preserve quota clamp/round tests and exhaustedWindowResetAt tests in separate describes.','rateLimits.test.ts; UsageFooter/UsageProviderChip tests; old-setting compatibility case'),
('CRLF editor lifecycle',['src/features/files/editor/editorDoc.test.ts','src/features/files/ui/FileEditor.tsx'],'weave','EditorDiskSession preserves disk and index EOL separately, logical-dirty check','normalize/detect/restore functions, staged-only lookup via gitDiffFiles, format-on-save/autosave','Keep EditorDiskSession as serializer; adopt gitDiffFiles staged/unstaged decision so true unstaged changes are not hidden by logical equality. Upstream normalization helpers must use the existing shared LineEnding type (R-03). Preserve diskSessionRef serializeForSave/serializeForStage and both test families; add autosave/format/CRLF/disk-conflict matrix.','editorDoc.test.ts; editorGit.test.ts; FileEditor.test.ts; lineEndings.test.ts'),
('File pane loading and filesystem bridge',['src/features/files/ui/FilePane.tsx','src/platform/tauri/fs.test.ts'],'weave','GitFileDiffView plus local wallpaper bridge tests','lazy surfaces/remote paths and pickFolders','Use upstream lazySurface/Suspense structure for shared viewers while retaining GitFileDiffView route for local diff tabs; preserve terminal branch. Union pickFolders and wallpaper test imports without replacing mocks or deleting assertions.','FilePane/WorkingTreeDiff tests; fs.test.ts; remote pane tests'),
('Pull review and CI repair',['src/features/inbox/ui/InboxView.tsx','src/features/inbox/ui/InboxView.test.ts'],'weave','CodeRabbit Pull review callbacks and hover continuity','GitHub job/check repair session callbacks and status marks','Carry onPullReview and repairSessions/onRepairChecks through every parent/detail component signature and JSX call; keep both InboxView and inboxStatusMark test imports. Preserve distinct review report vs CI prompt fields.','InboxView.test.ts; githubTasks.test.ts; ciRepair tests; new both-actions rendered case'),
('Notes restore and refresh',['src/features/notes/ui/NotesView.tsx'],'weave','remembered note selection, loading/error and hover system','selection restore-aware initialization; Operator notes-write refresh and markdown','Adopt upstream initializer that validates remembered selection against current notes, keep local loading/error and hover attributes; preserve notes-changed subscription.','notes.test.ts; NotesView.hover.test.ts; note-write tests'),
('Conversation persistence',['src/features/sessions/data/sessionStore.ts','src/features/sessions/data/sessionStore.test.ts',S+'model/session.ts'],'weave','branch origin/fork fields, token usage, review reports, durable queue fields and Cline','BTW/generated images/CI evidence/Operator/intent/background tasks and remote non-local save rule','Union optional fields and sanitizers; preserve sanitizeBranchOrigin and review alongside sanitizeNestedId/generated image/BTW routines. Keep providerForkPoint on users; retain ciContext and intent/monocode separately. Remote host-owned sessions stay out of local persistence; local queues remain persisted (correct misleading upstream in-memory comment). Never weaken identity validation.','sessionStore native-branch/queue tests plus BTW/generated-image/remote tests; SQL queue tests'),
('Durable queue and usage limits',[S+'model/messageQueue.ts',S+'model/messageQueue.test.ts'],'weave','held/steering/failed-turn and editing barriers','usageLimit blocks auto dispatch','Single canDispatchQueuedHead checks busy, usageLimit, paused/resuming/steering/held, preparing handoff and edited head. Preserve both held-failure and usage-limit tests; resume-at-reset must not release independent local held/paused reasons.','messageQueue/queueDurability/usageLimit tests; new held+reset and restart cases'),
('Answer actions and side conversations',[S+'ui/AgentTranscript.tsx',S+'ui/AgentTranscript.test.ts',S+'ui/SessionPane.tsx','src/features/workspace/ui/PaneTree.tsx'],'new product question','Sidechat/Branch/review-fix, session-scope approvals, forms and context meter','BTW sheet callbacks, remote session view, background tools/CI/image/animations','Keep scope-aware onApproval and McpFormReply through every layer, branch divider tests and all five BTW callbacks if D-01 accepts BTW. D-01 chooses which user-facing Sidechat/BTW actions coexist. Add backgroundTasks to scope-aware transcript props rather than reverting approval signature. Remote session rendering has explicit unsupported feature policy (D-03).','AgentTranscript/branchFlow/McpForm/ApprovalToasts tests; BTW/RemoteSession tests'),
('Composer routing',[S+'ui/Composer.tsx',S+'ui/Composer.test.ts'],'standing call','Queue/Steer buttons keep Stop, keyboard action resolver, form/question precedence','BTW/MCP/mode commands, awaited paste, remote plan gating, allowBusySubmit replacing Stop','Standing call NOTES §0.1 and archive 2026-09-23: retain canSteer/actionTooltip/actionAriaLabel/handleActionClick/executeComposerAction and dual Stop+send. Parse MCP/mode/BTW before selected local send/queue/steer dispatch, carry text/attachments/intents exactly once. Keep form priority and deterministic FileReader mock. Do not adopt allowBusySubmit stop-replacement branch.','Composer.test.ts Stop contract; composerAction tests; MCP forms/command/attachment and BTW tests'),
('Appearance and settings',['src/features/settings/model/appearance.ts','src/features/settings/model/settings.test.ts','src/features/settings/ui/SettingsView.tsx','src/styles/index.css'],'weave','Windows wallpaper/glass/fonts/hover/frame opacity; AI helper settings; discovery loading/retry/update toasts','Haze, Linux glass, provider scopes/binary UI, format-on-save/keybindings/MCP/scale menu','Union platform/color/storage imports. Keep all local initial appearance applications and stable Popover wash; carry upstream Linux/native theme options. Render AI helper and Editor groups separately. Compose provider scope controls with initialLoading/Recheck; D-02 selects updater UI, D-04 override store. Segmented options support disabled/title/description plus icon. Haze remains chat-only unless D-08 approves wallpaper support.','appearance/settings/wallpaper/hover/provider loading tests; scale/menu/MCP tests; Windows manual follow-up'),
('Changes review scope and line diff',[G+'model/unifiedDiff.ts',G+'ui/SourceControl.tsx',G+'ui/WorkingTreeDiff.tsx'],'weave','line-ending normalization and flexible staged/unstaged focus options','explicit section kind and line-based big-file diff','Union decodeLineEndings and LINE_DIFF_CONFIG imports; preserve normalizing input and use upstream line diff config. Thread staged/unstaged kind through Open All Changes; preserve focusPath without making section refresh lose selected file. Update direct consumers together.','unifiedDiff/gitText/WorkingTreeDiff tests; new selected-path+section switching case'),
('Commit/PR helper and cancellation',[G+'ui/GitChangesPanel.tsx',G+'ui/GitChangesPanel.test.ts',G+'ui/SwitchBranchDialog.tsx',G+'ui/SwitchBranchDialog.test.ts'],'new product question','selected helper model, structured PR draft dialog and no overwrite of human edits','abort controller/repeat-submit guards, remote PR content and cancel control','D-02/D-07 parameters: keep generateHelperCommitMessage/generateHelperPrContent for local calls with AbortSignal; adopt cancel UI and duplicate-generation guard, preserve startText comparison and helperFailureMessage. Remote content uses remote API; do not send remote cwd to local helper. Keep both add/add test suites after reconciling mocks once.','helperPipeline/PrDetailsDialog/GitChangesPanel/SwitchBranchDialog tests; add cancel+edited-field combination'),
('Workspace serialization and preview scope',['src/features/workspace/model/layout.ts','src/features/workspace/model/workspaceSnapshot.ts','src/features/workspace/model/workspaceSnapshot.test.ts'],'weave','diff/focusKind metadata and Windows encoded-drive repairs','preview tabs, remote-file discriminants, saved-model fallback and staged section kind','Union import lists; keep !file.diff in reusable editor predicate if local special diff viewer is retained. Validate diff/focusKind and remoteFile independently; remoteOwner maps remote paths, else apply repairLegacyEncodedDriveColon. model=stub.model||session.model avoids blank legacy models without catalog normalization.','workspaceSnapshot/layout/terminalPanes tests; old Windows snapshot + preview/remote tests'),
('Telemetry reducer',[H+'core/apply.ts'],'weave','stampTurnUsage/liveTurnUsage ownership and findTurnOwnerIndex','endedAt parameter/background-task clearing/intent/todo/image events','stopStreaming(session,endedAt=Date.now()) clears backgroundTasks and stamps local token usage before duration using active turn owner; keep findTurnOwnerIndex separate from stampTurnDuration(blocks,endedAt). Do not stamp most-recent internal synthetic user as owner.','tokenAccounting/tokenUsageLifecycle/apply tests; background/plan completion tests'),
('Harness interface union',[H+'core/registry.ts',H+'core/registry.test.ts',H+'index.ts'],'weave','runHelperPrompt/inspectContext/native fork/form/session approval APIs','runTextPrompt/stopTextPrompt/task-list restore/batched flush and cancellation','Keep HelperPromptInput/runHelperPrompt and TextPromptInput/runTextPrompt as distinct contracts; union adapter fields/exports and isolated cancellation. Do not route helper callers into general read-only tool-capable BTW by default (D-07). Extend tests to Cline explicit support/unsupported behavior rather than dropping its provider key.','registry/helperPipeline/native context tests; isolated text/BWT tests'),
('Removed upstream Antigravity provider',[H+'providers/antigravity/'+p for p in ['antigravity.ts','antigravityCatalog.ts','antigravityLive.test.ts','antigravityProtocol.test.ts']],'standing call','official shared ACP implementation moved to core; old provider tree intentionally removed','old provider binary-override/remote access/clipboard test edits','NOTES §0.3 / archive 2026-09-23 round2.1: retain deletion of these paths. Port relevant configurable-binary/clipboard tests into core ACP tests after verifying native contract. Repair host/providers import before remote host builds; do not resurrect AntigravityBinary/antigravity_args or duplicate command.','antigravityAcpLive/protocol/catalog/availability/helper tests; new host ACP integration missing'),
('Claude live provider union',[H+'providers/claude/'+p for p in ['claude.ts','claudeAdapter.ts','claudeLive.test.ts','claudeProtocol.test.ts']],'weave','session grants/live controls/native forks/context usage/human-origin helper isolation','streamed input/boundaries/background task lifecycle/task-list restores and text prompts','Union Live fields, task/grant maps and resets; keep delayed providerBound with reported fork ID. Preserve live model/permission controls and grant liveness checks; add pendingAssistantBoundary and background/task logic. Keep runHelperPrompt plus runTextPrompt/stopTextPrompt adapter methods. Union tests, not one test file per side.','ClaudeLive/Control/Protocol/Text and branch tests; combined fork/live-control/background tests'),
('Codex live provider union',[H+'providers/codex/'+p for p in ['codex.ts','codexAdapter.ts','codexElicitation.test.ts','codexLive.test.ts','codexProtocol.ts']],'weave','native fork, cumulative token baselines, MCP typed forms and guarded session grants','per-item text maps, image notifications, usage limits/Operator network state and all Full Access confirmations','Use emittedAssistantByItem/emittedReasoningByItem but retain threadBaseline/lastThreadTotal/turnUsage and inProgressMcpTools resets. In elicitation handler call codexMcpConfirmation with parent candidates; broaden only non-plan Full Access confirmation acceptance, then non-plan stored grant path, then explicit confirmation/form UI. Remove stale isCodexComputerUseAccessConfirmation import/call. Retain session grant liveness and form validation. Union protocol tokenUsage with usageLimited/rateLimits fields.','codexLive/Elicitation/Protocol/ApprovalUi, MCP forms and token accounting tests; new confirmation+grant+plan matrix'),
('Isolated helper versus read-only text runners',[H+'providers/claude/claudeText.ts',H+'providers/codex/codexText.ts',H+'providers/opencode/opencodeText.ts',H+'providers/opencode/opencodeText.test.ts',H+'providers/opencode/opencodeAdapter.ts'],'new product question','tools denied and HelperToolAttemptError aborts helper; structured output/model preference','read-only BTW tools/events/thread/settings/cancellation and configured runtime binaries','D-07 must keep isolated helper semantics. Add explicit helper isolation mode or retain a dedicated helper runner; noTools/max-turn/deny-all and outputSchema persist only for helper calls, upstream read-only BTW stays separate. Include isolation in reuse key so a tool-enabled runtime cannot serve helper calls. Carry AbortSignal cleanup and thread resume/settings logic without broadening helper permissions.','helperPipeline/ClaudeText/CodexText/OpenCodeText tests; new alternating helper/BTW account/model/isolation case'),
('Windows PTY event offsets',['src/platform/tauri/pty.ts','src/platform/tauri/pty.test.ts'],'weave','offset-aware replay and bytesSeen buffering','decodePtyChunk skips malformed base64','decodePtyChunk first; on null do not change bytesSeen or invoke handler. On valid chunk preserve start offset, update bytesSeen and pass offset to handler/pushBuffered. Union decode tests with replay/unsupported notification tests.','pty.test.ts; terminalSurfaceParity/TerminalView tests'),
]
seen=set();records=[]
for index,(name,paths,classification,local,upstream,seam,tests) in enumerate(groups,1):
    selected=[r for r in evidence if r['path'] in paths]
    assert len(selected)==len(paths),(name,set(paths)-{r['path'] for r in selected})
    for r in selected:assert r['path'] not in seen;seen.add(r['path'])
    hunk_count=sum(len(r['hunks']) for r in selected)
    lines=sum(len(h['ours'].splitlines())+len(h['theirs'].splitlines()) for r in selected for h in r['hunks'])
    size='L' if lines>150 else 'M' if lines>30 else 'S'
    records.append(dict(id=f'C-{index:02}',name=name,paths=paths,classification=classification,local=local,upstream=upstream,resolution=seam,tests=tests,hunks=hunk_count,side_lines=lines,size=size,u_ids=sorted(set(uid for r in selected for uid in r['u_ids'].split(',') if uid)),l_ids=sorted(set(lid for r in selected for lid in r['l_ids'].split(',') if lid))))
assert seen=={r['path'] for r in evidence}
risks=[
('New availability store omits Cline','typecheck; runtime split-store discovery','Verified `availabilityState.ts:8–20 @ 43aac9d` declares Record<HarnessId,boolean> with ten members; local session.ts:30 includes Cline. Local availability.ts retains its own evidenced state.','Add Cline and consolidate one store with local evidence/error semantics; preserve lazy ACP.','High','U-004','L-04,L-18'),
('Remote host imports the intentionally removed Antigravity provider','host typecheck/build after standing deletion; runtime','Verified `host/providers.ts:10,142 @ 43aac9d` imports/calls old module; C-23 requires deletion.','Port host adapter to core ACP with a verified Node-compatible transport, or explicitly disable remote ACP until that work is approved. Do not restore deleted provider.','High','U-023','L-03'),
('Clean editorDoc merge has duplicate LineEnding binding','typecheck','Verified scratch merged editorDoc.ts:7 imports LineEnding and :22 exports a separate LineEnding declaration. No Git conflict.','Use/re-export one shared sessions/model/lineEndings type; adapt upstream normalizers to existing encode/decode contract and retain disk/index serializers.','High','U-056','L-27'),
('Two persisted CLI override stores do not migrate automatically','runtime with existing settings','Verified local customBinary.ts:3 uses monocode.customBinary.<id>; new providerBinaryPaths.ts:6 uses monocode.providerBinaryPaths.v1.','D-04 chooses one store and explicit legacy migration/precedence; keep existing ACP/Cline overrides valid and backend authorization.','High','U-013','L-03,L-04,L-13,L-18'),
('Clean removal of Codex computer-use helper breaks whole-file local Codex selection','typecheck after an ours-only resolution','Verified upstream codexElicitation.ts deletes exported isCodexComputerUseAccessConfirmation; local Codex uses it. B merge keeps grants/forms but deletes helper.','C-25 removes import/call and uses broader non-plan Full Access only for recognized confirmations; no form auto-fill.','High','U-040','L-20,L-21,L-23'),
('New update notice blanket probes ACP and duplicates local notifications','runtime startup/processes and double notices','Verified HarnessUpdateNotice.ts:48 calls probeHarnessAvailability() before filtering updatable harnesses; local availability uses lazy exclude options, local ProvidersPage owns UpdateToasts.','D-02 chooses one notice flow; exclude ACP from blanket startup probes; keep explicit discovery and honest unknown states.','High','U-029','L-03,L-18'),
('Haze shares the effect union but wallpaper uses worker rendering','runtime when selecting Haze for wallpaper','Verified Haze gradient-blur bypasses applyPreparedNewThreadBackground worker conversion; local applyWallpaperPath calls renderWallpaper/prepareNewThreadBackgroundEffect. Inferred wallpaper Haze may take unsupported worker route.','D-08: keep Haze chat-only in round1; enumerate wallpaper five effects separately until native wallpaper Haze renderer/guard is approved.','Medium','U-002','L-09'),
('Remote feature support excludes Cline and local forms/session scopes','runtime UI and remote protocol','Verified REMOTE_PROVIDERS in connections/model/protocol.ts:7 has ten entries, no Cline; host approve signature accepts decision without ApprovalScope. Local UI forwards scope/forms.','D-03 choose explicit support matrix; local features preserved locally; remote hides unsupported scopes/forms rather than silently promising them. Extend protocol only with separate approval.','High','U-023','L-04,L-20,L-23,L-25'),
('Queue reset auto-resume can bypass independent holds','runtime/reset timer and restored data','Verified usageLimitResumeDue/add resume loop arrives in App; local queueStatus held/steering barriers are separate. Inferred interaction requires combined tests.','Keep held/paused reason authoritative; reset clears usage hold only. Add reset+held/restart tests before enabling automatic resume.','Medium','U-011','L-05,L-06'),
('Generated image cleanup and native fork copies may share asset IDs','runtime when deleting a copied branch','Verified generated-image save/delete commands and local forkThreadBlocks copy transcript metadata. Not checked cross-branch asset-reference ownership.','Audit cleanup against all saved branch references; add original/branch deletion round-trip before shipping copied image history.','Medium','U-020','L-25'),
('New host pipeline adds independent build/runtime requirements','host typecheck/build; packaging/CI','Verified package scripts host:build/test:host and host/tsconfig; CI host packages/Node24, dev esbuild/@types/node.','Owner approve CI/dependencies; later worker runs host gates as well as web/Rust. Analysis performed no install/check.','High','U-023,U-067,U-077','L-13'),
('Native bridge/search union must preserve queue SQL and hidden process behavior','Rust typecheck/tests; Windows runtime/old DB','Verified SQL v14 queued columns local; upstream18 remains endpoint. Conflict search converts Command to argument vector; new modules spawn subprocesses. Full new spawn-path audit Not checked.','Preserve column/placeholder/mapper alignment, Windows cwd alternatives and helper suppression. Audit every added spawn before enabling updates/remote.','Medium','U-064,U-029,U-023','L-05,L-13'),
('Exact test lists may encode upstream ten providers or UI text','tests','Verified registry.test.ts source provider-support list lacks local Cline; ModelPicker.test still asserts 440/442 and quota tests differ used/left text.','Add Cline support/explicit unsupported classification to new test lists; keep old local dimensions; D-06 controls quota text. Never weaken tests to green.','High','U-008,U-027','L-04,L-12'),
('Old snapshots must union remote/preview discriminants with local diff metadata','runtime restore/old data','Verified workspaceSnapshot.ts conflict compares remoteFile/remoteOwner against diff/focusKind/drive-colon repair. New fields absent in old records.','Restore absent fields with backward defaults; retain validation of local diff/focusKind and legacy drive normalization only for local paths; add persisted fixture matrix.','Medium','U-005,U-023','L-07,L-08,L-16'),
('New read-only text runtimes cannot replace tool-free helpers','runtime helper isolation','Verified ClaudeText hunk switches noTools:true to settings permission/maxTurns; CodexText changes item/started tool rejection to event forwarding; OpenCodeText no longer rejects helper tool parts.','D-07 must require distinct helper isolation/reuse key; structured output and fail-closed tool attempt regressions remain.','High','U-008','L-19'),
]
rrecords=[dict(id=f'R-{n:02}',name=r[0],when=r[1],evidence=r[2],handling=r[3],confidence=r[4],u_ids=r[5],l_ids=r[6]) for n,r in enumerate(risks,1)]
OUT.joinpath('scripts/analysis.json').write_text(json.dumps(dict(conflicts=records,risks=rrecords),indent=2),encoding='utf-8')
md=['# Stage 4 — Conflicts and risks','','Verified: 80 actual paths assigned exactly once to 27 C groups; 231 textual marker hunks (modify/delete paths have zero marker hunks). Hunk count/size measured by scripts/conflict-evidence.py. S ≤30, M 31–150, L >150 combined side lines; size is textual load, not duration. `scripts/hunk-review.md` was read for every hunk; full side diffs are retained in evidence JSON. Recommendations are **Inferred** from source seams, provisional until owner decisions and checks. No conflict was resolved.','','## Summary','','| ID | Paths | Class | Hunks / size | Recommendation |','|---|---|---|---|---|']
for c in records:md.append(f"| {c['id']} {c['name']} | "+'; '.join('`'+p+'`' for p in c['paths'])+f" | {c['classification']} | {c['hunks']} / {c['size']} ({c['side_lines']} side lines) | {c['resolution']} |")
for c in records:
    md += ['',f"## {c['id']} — {c['name']}",f"- Local: {c['local']}.",f"- Upstream: {c['upstream']}.",f"- Trace: {', '.join(c['u_ids'])}; {', '.join(c['l_ids']) or 'additional local seam documented in side diff'}.",f"- Class: {c['classification']}; {c['hunks']} hunks; {c['size']}.",f"- Taking local whole loses: {c['upstream']}.",f"- Taking upstream whole loses: {c['local']}.",f"- Recommended (Inferred): {c['resolution']}",f"- Existing verification suites / missing cases: {c['tests']}.",'- Confidence: Medium for integration design; High for exact hunk/path evidence. Not checked: compilation, tests or runtime; largest full-contract audits remain below.','', '| Exact path | Verified marker lines in scratch merged blob | Side-diff evidence |','|---|---|---|']
    for p in c['paths']:
        r=next(r for r in evidence if r['path']==p)
        md.append(f"| `{p}` | {', '.join(str(h['line']) for h in r['hunks']) or 'modify/delete stage entries; no markers'} | local {r['ours_diff_lines']} / upstream {r['upstream_diff_lines']} lines; full text in conflict-evidence.json keyed by path |")
md+=['','## Risks without a textual conflict','','| ID | What breaks / when | Evidence | Proposed handling | Confidence |','|---|---|---|---|']
for r in rrecords:md.append(f"| {r['id']} {r['name']} ({r['u_ids']}; {r['l_ids']}) | {r['when']} | {r['evidence']} | {r['handling']} | {r['confidence']} (source; runtime Not checked) |")
md+=['','## Clean-merge preservation review','','Verified: all 47 B blobs were read by `scripts/clean-audit.py`; the 201-line result was reviewed. Selected local added declarations survive textually in every B file examined. This does not prove runtime wiring. R-03 demonstrates why declaration survival alone is insufficient. Full per-path structural result is in scripts/clean-merge-audit.md.','', '- L-14: Windows ConPTY/replay added lines survive in pty.rs; incoming Linux c_char fix is unrelated to Windows path.','- L-08: DormantTerminalView/start lifecycle survives TerminalView.tsx; App close paths still require C-06.','- L-09/L-19: wallpaper/helper storage functions and tests survive clean settings.ts; C-17 must keep UI wiring and new effects guarded.','- L-10: SharedHoverHighlight remains in Popover frame; Quick composer updates positioning/backdrop options, so desktop geometry still needs later verification.','- L-20/L-23: grants/form parsing survives codexElicitation.ts while deprecated confirmation helper is removed (R-05).','- L-22/L-24/L-25/L-28: live-control/context/branch/human-origin declarations survive ClaudeProtocol and types; live-provider callers conflict and require C-24/C-25.','- L-25: OpenCode native-fork path survives its clean provider file and tests; helper text runner is a separate conflict.','- Local docs/jira.md and docs/screenshot.jpg deletions do not conflict: upstream did not change them in this range. No renames upstream; local Antigravity adapter R072 is the only detected local source move.','','## Not analysed deeply — exact paths and reason','','The following gaps remain **Not checked**. Every X path has hunk-level analysis above, but full bodies of large side diffs were sampled, not exhaustively audited. These are review requirements, not permission for a worker to guess.']
deep=[r['path'] for r in evidence if r['ours_diff_lines']+r['upstream_diff_lines']>1500]
md += [f'- `{p}`: full contract/control-flow audit beyond marker seams remains; source diff exceeds 1,500 combined lines.' for p in deep]
md += [f"- `{r['path']} @ 43aac9d`: remote-host module full security/persistence/transport audit not completed; only feature declarations and known ACP import/provider matrix reviewed." for r in manifest['rows'] if r['path'].startswith('host/')]
md += ['- `src-tauri/src/mcp.rs @ 43aac9d`: provider config-write compatibility with every CLI version not checked.','- `src-tauri/src/remote.rs @ 43aac9d`, `src-tauri/src/remote_ssh.rs @ 43aac9d`, `src-tauri/src/harness_updates.rs @ 43aac9d`: full security/process-spawn audit not completed.','- `src/features/settings/model/appearance.ts`: Haze wallpaper compatibility remains Inferred; round1 can safely retain original five wallpaper choices pending D-08.']
OUT.joinpath('04-conflicts-and-risks.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
print({'C_groups':len(records),'paths':len(seen),'R_items':len(rrecords),'L_groups':[(c['id'],c['hunks'],c['side_lines']) for c in records if c['size']=='L']})
